ZON-4709: Add author push as default
ZeitOnline/zeit.push pull request #27
Opened 2018-05-31 12:19 UTC by knutgoetz

Needs https://github.com/ZeitOnline/zeit.cms/pull/83

2018-06-06 14:25 UTC, wosc requested changes
Also ~die Ente~ der pdb bleibt draußen! ;)

2018-06-06 14:25 UTC, wosc commented on src/zeit/push/urbanairship.py
> +            if author_reference.target.enable_followpush:
Ich glaub die Defensivität muss man umdrehen. IUUID "kann" nicht fehlschlagen, aber im `target` steht evtl nix drin (Objekt gelöscht, etc.pp.)

```python
for ref in self.context.authorships:
    author = ref.target
    if author is not None and author.enable_followpush:
        result.append(IUUID(author).shortened)
```

2018-06-06 14:25 UTC, wosc commented on src/zeit/push/urbanairship.py
> +                # Use shortened id. Friedbert adds them to UA
Cross-Referenzen find ich hervorragend! Man könnte sogar auf die genaue Stelle verweisen (á la `zeit.web.site.view_author.Author.followpush_config`).

2018-06-06 14:25 UTC, wosc commented on src/zeit/push/urbanairship.py
> +    import pdb; pdb.set_trace()
Hüstel. Kann ich ggf. Werbung für http://github.com/wosc/git-codesmell machen? ;)
... und für nen Test, der nen Artikel anlegt und checkt dass es auch drinsteht.

2018-06-06 14:25 UTC, wosc commented on src/zeit/push/testing.py
> +    def create_template(self, text=None, name='template.json', available=True):
Wofür ist das `available` da?

2018-06-07 07:21 UTC, knutgoetz commented on src/zeit/push/testing.py
> +    def create_template(self, text=None, name='template.json', available=True):
Oopsala, da habe ich mein diff nicht vernünftig angeschaut, das ist ein Relikt. Ich fixe die Sachen.

2018-06-08 08:45 UTC, wosc reviewed
![push](https://media.giphy.com/media/K0QQmcCln2KJy/giphy.gif)

2018-06-08 08:45 UTC, merged