ZON-3213: Abort push to Urban Airship if no channel was given
ZeitOnline/zeit.push pull request #8
Opened 2016-09-23 11:30 UTC by florianpilz

Zurzeit ist es möglich, bei Fehlkonfiguration einen Push an *alle* Nutzer zu schicken. Egal ob News, Eilmeldung oder kein Abo. Mittlerweile halte ich diesen Default für gefährlich und würde lieber abbrechen.

Durch den AttributeError sieht man auch eine Meldung im ILog.

2016-09-26 06:01 UTC, sallner reviewed
LGTM.

2016-09-26 14:22 UTC, wosc commented on src/zeit/push/urbanairship.py
> +            raise AttributeError('No channel given to define target audience.')
So weit ich die stdlib-Doku verstehe, ist AttributeError nur für "Objekt kennt Namen nicht". Für den vorliegen Fall soll man glaube ich ValueError nehmen.

2016-09-26 14:22 UTC, wosc requested changes
Klingt sehr sinnvoll, man sollte aber glaub ich ne andere Exception werfen.

2016-09-28 06:53 UTC, wosc approved these changes

2016-09-28 06:54 UTC, merged

2016-09-28 16:09 UTC, florianpilz commented
Danke fürs kümmern. 🎁